services:
  discord-serverbrowser:
    container_name: discord-serverbrowser
    build: .
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      # - ./data:/app/data
    network_mode: bridge
